### ISSUE TITLE
./dvb.sh: cannot execute: required file not found

### ISSUE THREAD

**Issue by pszemus** [EricBerendsen/dvbinspector#57] opened 2023-01-18 08:57 UTC
```
[DVBinspector-1.17.0]$ ./dvb.sh 
bash: ./dvb.sh: cannot execute: required file not found
```

`dvb.sh` has CRLF line endings:

``` 
[DVBinspector-1.17.0]$ hexdump -C dvb.sh 
00000000  23 21 2f 62 69 6e 2f 62  61 73 68 0d 0a 6a 61 76  |#!/bin/bash..jav|
```

- `0d` - CR
- `0a` - LF

After changing line endings to LF only, `dvb.sh` runs successfully.

**Comment by EricBerendsen** [comment] 2023-01-18 12:22
Hi, 

Thank you for reporting this, but this is a duplicate of #56 It has been fixed and will be part of the next release.

**Closed** 2023-01-18 12:22 UTC
Labels: duplicate
