### ISSUE TITLE
Linux and ^M in the dvb.sh

### ISSUE THREAD

**Issue by luciust** [EricBerendsen/dvbinspector#59] opened 2023-04-12 08:10 UTC
Hello,

latest release ZIP has dvb.sh for UNIX systems with extra ^M at the end of each line. Thus making the script spit out error as the shell interprets the /bin/bash^M as non existent. The fix is to remove those extra chars at the end of line, easiest with mcedit from mc (Midnight Commander) package.
On other note - OpenJDK 17 seems to work fine with dvbinspector.

**Comment by EricBerendsen** [comment] 2023-04-23 19:19
Hi, Thank you for reporting this. It is a known bug (duplicate of #57 and #56 It has been fixed, but not released yet. I was not aware so many people use linux and the .sh file.

**Closed by EricBerendsen** 2023-04-23 19:19 UTC
